name: Update Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required to push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Graphic
        uses: Platane/snk@v3
        with:
          github_user_name: mdonnamadeline
          outputs: |
            assets/github-snake.svg

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-snake.svg
          git commit -m "Update snake animation"
          git push
